import type { InterfaceLanguage } from '@/models/profile';

type PhraseMap = Record<string, string>;

const uk: PhraseMap = {
  'Your balance': 'Ваш баланс', 'Spark wallet': 'Гаманець Sparks', 'Immutable history': 'Незмінна історія',
  'Recent activity': 'Остання активність', 'Latest': 'Останні', 'Quarter snapshot': 'Підсумок кварталу',
  'Your impact': 'Ваш внесок', 'Recognize a colleague': 'Відзначити колегу', 'Review approvals': 'Переглянути погодження',
  'Open administration': 'Відкрити адміністрування', 'Explore achievements': 'Переглянути досягнення',
  'Manage Spark rules': 'Керувати правилами Sparks', 'No transactions yet': 'Транзакцій ще немає',
  'Credits, conversions and disenchant requests for this employee will appear here.': 'Тут з’являться нарахування, конвертації та запити цього працівника.',
  'Your work is creating momentum. Here is how it is being recognized.': 'Ваша робота створює поступ. Ось як її відзначають.',
  'Every recognition keeps its story, even when the related Sparks are converted or spent.': 'Кожне визнання зберігає свою історію, навіть після конвертації або витрати Sparks.',
  'Focus mode active': 'Режим фокусу активний', 'VIP active': 'VIP активний', 'Active rewards': 'Активні нагороди',
  'Rewards marketplace': 'Маркетплейс нагород', 'Reward Shop': 'Магазин нагород',
  'Spend your existing White, Yellow and Blue Sparks on abilities and exclusive rewards.': 'Витрачайте наявні White, Yellow і Blue Sparks на можливості та ексклюзивні нагороди.',
  'Your spendable Sparks': 'Доступні Sparks', 'Synced with My Sparks · Radiant remains permanent': 'Синхронізовано з Мої Sparks · Radiant залишається постійним',
  'All items': 'Усі товари', 'Popular': 'Популярне', 'Boosters': 'Бустери', 'Customization': 'Персоналізація',
  'Abilities': 'Можливості', 'Exclusive': 'Ексклюзивне', 'Most popular': 'За популярністю',
  'Price: low to high': 'Спочатку дешевші', 'Price: high to low': 'Спочатку дорожчі', 'Newest': 'Новинки',
  'Buy': 'Купити', 'Not enough Sparks': 'Недостатньо Sparks', 'Already purchased': 'Уже придбано',
  'Use': 'Використати', 'Activate': 'Активувати', 'Activated': 'Активовано', 'Sold out': 'Продано',
  'Coming soon': 'Незабаром', 'Processing…': 'Обробка…', 'Price': 'Ціна', 'Category': 'Категорія',
  'Rarity': 'Рідкість', 'Duration': 'Тривалість', 'Purchased': 'Придбано', 'Available until': 'Доступно до',
  'New': 'Новинка', 'Limited': 'Обмежено', 'Common': 'Звичайний', 'Rare': 'Рідкісний', 'Epic': 'Епічний',
  'Legendary': 'Легендарний', 'Confirm purchase': 'Підтвердьте покупку', 'Current balance': 'Поточний баланс',
  'Balance after purchase': 'Баланс після покупки', 'Cancel': 'Скасувати', 'Purchase complete!': 'Покупку завершено!',
  'The reward is now available in your inventory.': 'Нагорода вже доступна у вашому інвентарі.',
  'Open inventory': 'Відкрити інвентар', 'Continue shopping': 'Продовжити покупки', 'Go to My Sparks': 'Перейти до Мої Sparks',
  'Personal collection': 'Особиста колекція', 'My Purchases': 'Мої покупки',
  'Activate purchased rewards and keep track of their availability.': 'Активуйте придбані нагороди та стежте за їх доступністю.',
  'Ready to use': 'Готово до використання', 'Used': 'Використано', 'Expired': 'Термін минув',
  'Transaction History': 'Історія транзакцій', 'Reward Shop activity': 'Активність магазину нагород',
  'Transactions cannot be edited or deleted.': 'Транзакції не можна редагувати або видаляти.',
  'All transactions': 'Усі операції', 'Purchases': 'Покупки', 'Credits': 'Нарахування', 'Refunds': 'Повернення',
  'Completed': 'Завершено', 'Purchase': 'Покупка', 'Refund': 'Повернення', 'Manual credit': 'Ручне нарахування',
  'Manual debit': 'Ручне списання', 'There are no transactions yet.': 'Транзакцій ще немає.',
  'Double White Sparks': 'Подвійні White Sparks', 'Earn twice as many White Sparks from completed activities for 24 hours.': 'Отримуйте вдвічі більше White Sparks за виконані активності протягом 24 годин.',
  'Streak Shield': 'Захист серії', 'Protect your current activity streak when you miss one day.': 'Зберігає поточну серію активності, якщо ви пропустите один день.',
  'Neon Interface Theme': 'Неонова тема інтерфейсу', 'Unlock an exclusive neon theme for your C-Job Sparks workspace.': 'Відкриває ексклюзивну неонову тему робочого простору C-Job Sparks.',
  'Golden Profile Frame': 'Золота рамка профілю', 'Add an animated golden frame to your profile avatar.': 'Додає анімовану золоту рамку до аватара профілю.',
  'Signature Badge': 'Фірмовий значок', 'Unlock an exclusive badge for your employee profile.': 'Відкриває ексклюзивний значок для профілю працівника.',
  'Mission Reroll': 'Повтор місії', 'Replace one mission that does not fit your current workload.': 'Дозволяє замінити одну місію, яка не відповідає поточному навантаженню.',
  'Mystery Reward Pack': 'Таємний набір нагород', 'Receive one random reward of Rare quality or higher.': 'Містить одну випадкову нагороду рідкісної або вищої якості.',
  '7-Day VIP Status': 'VIP-статус на 7 днів', 'Get an exclusive status badge and additional benefits for one week.': 'Надає ексклюзивний статус, значок і додаткові переваги на тиждень.',
  'Focus Beacon': 'Маяк фокусу', 'Unlock a distraction-free dashboard mode and keep your active mission highlighted for 24 hours.': 'Вмикає режим без відволікань і підсвічує активну місію протягом 24 годин.',
  "Captain's Mystery Crate": 'Таємна скриня капітана', 'Open a curated reward containing one customization item of Rare quality or higher.': 'Відкрийте нагороду з одним предметом персоналізації рідкісної або вищої якості.',
  'Personal ledger': 'Особистий реєстр', 'Every credit and debit remains visible. Your balance is calculated from this immutable history.': 'Кожне нарахування та списання залишається видимим. Баланс обчислюється з цієї незмінної історії.',
  'Spark Ledger': 'Реєстр Sparks', 'Search source or category': 'Пошук за джерелом або категорією',
  'No matching transactions': 'Відповідних транзакцій немає', 'Try a different Spark type, direction or search term.': 'Спробуйте інший тип Spark, напрямок або пошуковий запит.',
  'Permanent record': 'Постійний запис', 'My achievements': 'Мої досягнення', 'Lifetime earnings': 'Нагороди за весь час',
  'No achievements in this view': 'У цьому поданні немає досягнень', 'Choose another Spark type to see your recognition history.': 'Виберіть інший тип Spark, щоб переглянути історію визнання.',
  'Automatic recognition': 'Автоматичне визнання', 'My performance': 'Мої результати', 'Latest KPI': 'Останній KPI',
  'Personal cards reward': 'Нагорода за персональні картки', 'Validated results': 'Підтверджені результати',
  'Quarterly performance': 'Квартальні результати', 'Separate scales': 'Окремі шкали',
  'Peer recognition': 'Визнання колег', 'Make great work visible': 'Зробіть чудову роботу помітною',
  'New recognition': 'Нове визнання', 'Recognition status': 'Статус визнання', 'No requests yet': 'Запитів ще немає',
  'Your sent nominations and their decisions will appear here.': 'Тут з’являться надіслані номінації та рішення щодо них.',
  'Spark economy': 'Економіка Sparks', 'Convert Sparks': 'Конвертувати Sparks', 'From your balance': 'З вашого балансу',
  'You receive': 'Ви отримаєте', 'Before you convert': 'Перед конвертацією', 'Confirm Spark conversion': 'Підтвердьте конвертацію Sparks',
  'Accounting request': 'Запит до бухгалтерії', 'Disenchant Sparks': 'Розпилити Sparks', 'Spark type': 'Тип Spark',
  'Amount': 'Кількість', 'Estimated money value': 'Орієнтовна грошова вартість', 'Current C-Job policy.': 'Поточна політика C-Job.',
  'Monthly workflow': 'Щомісячний процес', 'What happens next': 'Що буде далі', 'Sparks debit immediately': 'Sparks списуються одразу',
  'Request enters accounting': 'Запит надходить до бухгалтерії', 'Payroll handles payment': 'Виплату обробляє бухгалтерія',
  'Review disenchant': 'Перевірити розпилення', 'Confirm disenchant': 'Підтвердьте розпилення', 'Confirm request': 'Підтвердити запит',
  'Transparent system': 'Прозора система', 'C-Job Sparks rules — from A to Z': 'Правила C-Job Sparks — від А до Я',
  'Recognition should be visible, fair and traceable': 'Визнання має бути видимим, справедливим і відстежуваним',
  'What each Spark means': 'Що означає кожен Spark', 'Quarterly nominations': 'Квартальні номінації',
  'Role permissions': 'Права ролей', 'Who approves each reward': 'Хто погоджує кожну нагороду',
  'KPI and personal cards rewards': 'Нагороди за KPI та персональні картки', 'Categories and safeguards': 'Категорії та запобіжники',
  'Convert and disenchant': 'Конвертація та розпилення', 'What never happens silently': 'Що ніколи не відбувається непомітно',
  'Who appears in each team': 'Хто входить до кожної команди', 'Head of Department': 'Керівник відділу',
  'Approval Center': 'Центр погоджень', 'Approval queue is clear': 'Черга погоджень порожня',
  'Reject request': 'Відхилити запит', 'Approve': 'Погодити', 'Reject': 'Відхилити',
  'System administration': 'Системне адміністрування', 'Admin Settings': 'Налаштування адміністратора',
  'Access': 'Доступ', 'Shop': 'Магазин', 'Import': 'Імпорт', 'Directory': 'Довідник', 'Audit': 'Аудит',
  'Prepare a validated batch': 'Підготуйте перевірений пакет', 'Validation sequence': 'Послідовність перевірки',
  'Recent system events': 'Останні системні події', 'Administrator invariant': 'Інваріант адміністратора',
  'Try again': 'Спробувати ще', 'Save': 'Зберегти', 'Edit': 'Редагувати', 'Close': 'Закрити',
  'Active': 'Активний', 'Disabled': 'Вимкнено', 'Loading workspace section…': 'Завантаження розділу…',
  'This workspace is not available': 'Цей простір недоступний', 'This Spark trail ends here': 'Цей шлях Sparks закінчується тут',
  'The requested page is not part of the C-Job Sparks workspace.': 'Запитана сторінка не належить до робочого простору C-Job Sparks.',
  'One place for every contribution.': 'Одне місце для кожного внеску.',
  'Sign in to recognize colleagues, follow your Sparks and celebrate work that moves C-Job forward.': 'Увійдіть, щоб відзначати колег, стежити за Sparks і цінувати роботу, що рухає C-Job уперед.',
  'Access follows the role in the employee directory.': 'Доступ визначається роллю у довіднику працівників.',
  'Sign in to C-Job Sparks': 'Увійти до C-Job Sparks', 'Create your account': 'Створити обліковий запис',
  'Use your approved work account to open your Spark workspace.': 'Використайте підтверджений робочий обліковий запис, щоб відкрити простір Sparks.',
  'Request access with your directory email. An administrator must approve it before the first sign-in.': 'Запросіть доступ за допомогою email із довідника. Перед першим входом запит має погодити адміністратор.',
  'Work email': 'Робочий email', 'Password': 'Пароль', 'Confirm password': 'Підтвердьте пароль',
  'Sign in': 'Увійти', 'Request access': 'Запросити доступ', 'Need an account?': 'Потрібен обліковий запис?',
  'Already have access?': 'Уже маєте доступ?', 'Try an approved role': 'Спробувати погоджену роль',
  'Welcome back': 'З поверненням', 'Local demo access': 'Локальний демо-доступ',
  'Local browser demo · approvals are not shared with other devices · do not use real credentials': 'Локальна браузерна демоверсія · погодження не синхронізуються з іншими пристроями · не використовуйте справжні облікові дані',
  'Skip to account content': 'Перейти до вмісту облікового запису', 'Recognition with purpose': 'Визнання зі змістом',
  'Show password': 'Показати пароль', 'Hide password': 'Приховати пароль',
  'Show passwords': 'Показати паролі', 'Hide passwords': 'Приховати паролі', 'Please wait…': 'Зачекайте…',
  'Submit for approval': 'Надіслати на погодження', 'Already approved?': 'Доступ уже погоджено?',
  'Try the approval flow': 'Спробувати процес погодження', 'Password requirements': 'Вимоги до пароля',
  '8+ characters': 'Щонайменше 8 символів', 'Upper & lowercase': 'Великі й малі літери',
  'At least one number': 'Щонайменше одна цифра', 'Met': 'Виконано', 'Not met': 'Не виконано',
  'Employee': 'Працівник', 'Coordinator': 'Координатор', 'Head': 'Керівник',
  'Top Management': 'Топменеджмент', 'Administrator': 'Адміністратор',
  'Choose a demo directory profile': 'Виберіть демо-профіль із довідника', 'More demo roles': 'Інші демо-ролі',
  'No registration in progress': 'Немає активного запиту на реєстрацію', 'Access approved': 'Доступ погоджено',
  'Request needs attention': 'Запит потребує уваги', 'Approval pending': 'Очікує погодження', 'Administrator note': 'Примітка адміністратора',
  'Award a Radiant Spark': 'Нагородити Radiant Spark', 'Award a Spark': 'Нагородити Spark', 'Award details': 'Деталі нагороди',
  'Reward': 'Нагорода', 'Choose a category': 'Виберіть категорію', 'Award date': 'Дата нагороди',
  'Select an employee': 'Виберіть працівника', 'Live preview': 'Попередній перегляд', 'Award history': 'Історія нагород',
  'Your first award starts here': 'Ваша перша нагорода починається тут',
  'Submitted requests and direct awards will appear here with their current status.': 'Надіслані запити та прямі нагороди з’являться тут із поточним статусом.',
  'No people found': 'Людей не знайдено', 'Try a different search term.': 'Спробуйте інший пошуковий запит.',
  'Search people': 'Пошук людей', 'Quality Gates': 'Quality Gates', 'Disenchant requests': 'Запити на розпилення',
  'Shop items': 'Товари магазину', 'Add item': 'Додати товар', 'Adjust Spark balance': 'Змінити баланс Sparks',
  'Recent purchases': 'Останні покупки', 'New item': 'Новий товар', 'Edit item': 'Редагувати товар',
  'Save item': 'Зберегти товар', 'Upload image': 'Завантажити зображення', 'Name': 'Назва', 'Description': 'Опис',
  'Good morning': 'Доброго ранку', 'Good afternoon': 'Добрий день', 'Good evening': 'Добрий вечір',
  'Everyday recognition': 'Щоденне визнання', 'Significant contribution': 'Значний внесок',
  'Long-term impact': 'Довготривалий вплив', 'Company-wide distinction': 'Відзнака на рівні компанії',
  'achievements received': 'отримано досягнень', 'categories': 'категорії',
  'lifetime achievements': 'досягнення за весь час', 'latest KPI': 'останній KPI',
};

const ru: PhraseMap = {
  'Your balance': 'Ваш баланс', 'Spark wallet': 'Кошелёк Sparks', 'Immutable history': 'Неизменяемая история',
  'Recent activity': 'Последняя активность', 'Latest': 'Последние', 'Quarter snapshot': 'Итоги квартала',
  'Your impact': 'Ваш вклад', 'Recognize a colleague': 'Отметить коллегу', 'Review approvals': 'Проверить согласования',
  'Open administration': 'Открыть администрирование', 'Explore achievements': 'Посмотреть достижения',
  'Rewards marketplace': 'Маркетплейс наград', 'Reward Shop': 'Магазин наград',
  'Spend your existing White, Yellow and Blue Sparks on abilities and exclusive rewards.': 'Используйте накопленные White, Yellow и Blue Sparks для возможностей и эксклюзивных наград.',
  'Your spendable Sparks': 'Доступные Sparks', 'All items': 'Все товары', 'Popular': 'Популярное',
  'Boosters': 'Бустеры', 'Customization': 'Персонализация', 'Abilities': 'Возможности', 'Exclusive': 'Эксклюзивное',
  'Most popular': 'По популярности', 'Price: low to high': 'Сначала дешевле', 'Price: high to low': 'Сначала дороже',
  'Newest': 'Новинки', 'Buy': 'Купить', 'Not enough Sparks': 'Недостаточно Sparks', 'Already purchased': 'Уже куплено',
  'Use': 'Использовать', 'Activate': 'Активировать', 'Activated': 'Активировано', 'Sold out': 'Продано',
  'Coming soon': 'Скоро', 'Processing…': 'Обработка…', 'Price': 'Цена', 'Category': 'Категория',
  'Rarity': 'Редкость', 'Duration': 'Срок действия', 'Purchased': 'Куплено', 'Available until': 'Доступно до',
  'New': 'Новинка', 'Limited': 'Ограничено', 'Common': 'Обычный', 'Rare': 'Редкий', 'Epic': 'Эпический',
  'Legendary': 'Легендарный', 'Confirm purchase': 'Подтвердите покупку', 'Current balance': 'Текущий баланс',
  'Balance after purchase': 'Баланс после покупки', 'Cancel': 'Отмена', 'Purchase complete!': 'Покупка завершена!',
  'Open inventory': 'Открыть инвентарь', 'Continue shopping': 'Продолжить покупки', 'Personal collection': 'Личная коллекция',
  'My Purchases': 'Мои покупки', 'Ready to use': 'Готово к использованию', 'Used': 'Использовано', 'Expired': 'Истёк срок',
  'Transaction History': 'История покупок', 'All transactions': 'Все операции', 'Purchases': 'Покупки',
  'Credits': 'Начисления', 'Refunds': 'Возвраты', 'Completed': 'Завершено', 'Purchase': 'Покупка', 'Refund': 'Возврат',
  'Double White Sparks': 'Двойные White Sparks', 'Streak Shield': 'Защита серии', 'Neon Interface Theme': 'Неоновая тема интерфейса',
  'Golden Profile Frame': 'Золотая рамка профиля', 'Signature Badge': 'Персональный значок', 'Mission Reroll': 'Повтор задания',
  'Mystery Reward Pack': 'Секретный набор', '7-Day VIP Status': 'VIP-статус на 7 дней', 'Focus Beacon': 'Маяк фокуса',
  "Captain's Mystery Crate": 'Секретный ящик капитана', 'Personal ledger': 'Личный реестр', 'Spark Ledger': 'Реестр Sparks',
  'Permanent record': 'Постоянная запись', 'My achievements': 'Мои достижения', 'Lifetime earnings': 'Награды за всё время',
  'Automatic recognition': 'Автоматическое признание', 'My performance': 'Мои результаты', 'Latest KPI': 'Последний KPI',
  'Personal cards reward': 'Награда за персональные карточки', 'Validated results': 'Подтверждённые результаты',
  'Quarterly performance': 'Квартальные результаты', 'Peer recognition': 'Признание коллег',
  'Make great work visible': 'Сделайте отличную работу заметной', 'New recognition': 'Новое признание',
  'Recognition status': 'Статус признания', 'Spark economy': 'Экономика Sparks', 'Convert Sparks': 'Конвертировать Sparks',
  'From your balance': 'Из вашего баланса', 'You receive': 'Вы получите', 'Before you convert': 'Перед конвертацией',
  'Accounting request': 'Запрос в бухгалтерию', 'Disenchant Sparks': 'Распылить Sparks', 'Spark type': 'Тип Spark',
  'Amount': 'Количество', 'Estimated money value': 'Ориентировочная денежная стоимость', 'Current C-Job policy.': 'Текущая политика C-Job.',
  'Monthly workflow': 'Ежемесячный процесс', 'What happens next': 'Что произойдёт дальше', 'Review disenchant': 'Проверить распыление',
  'Confirm disenchant': 'Подтвердите распыление', 'Confirm request': 'Подтвердить запрос', 'Transparent system': 'Прозрачная система',
  'C-Job Sparks rules — from A to Z': 'Правила C-Job Sparks — от А до Я', 'Role permissions': 'Права ролей',
  'Convert and disenchant': 'Конвертация и распыление', 'Head of Department': 'Руководитель отдела',
  'Approval Center': 'Центр согласований', 'Approval queue is clear': 'Очередь согласований пуста',
  'Reject request': 'Отклонить запрос', 'Approve': 'Согласовать', 'Reject': 'Отклонить',
  'System administration': 'Системное администрирование', 'Admin Settings': 'Настройки администратора',
  'Access': 'Доступ', 'Shop': 'Магазин', 'Import': 'Импорт', 'Directory': 'Справочник', 'Audit': 'Аудит',
  'Try again': 'Попробовать снова', 'Save': 'Сохранить', 'Edit': 'Редактировать', 'Close': 'Закрыть',
  'Active': 'Активный', 'Disabled': 'Отключено', 'Loading workspace section…': 'Загрузка раздела…',
  'This workspace is not available': 'Это пространство недоступно', 'This Spark trail ends here': 'Этот путь Sparks заканчивается здесь',
  'The requested page is not part of the C-Job Sparks workspace.': 'Запрошенная страница не относится к рабочему пространству C-Job Sparks.',
  'One place for every contribution.': 'Одно место для каждого вклада.',
  'Sign in to recognize colleagues, follow your Sparks and celebrate work that moves C-Job forward.': 'Войдите, чтобы отмечать коллег, следить за Sparks и ценить работу, которая двигает C-Job вперёд.',
  'Access follows the role in the employee directory.': 'Доступ определяется ролью в справочнике сотрудников.',
  'Sign in to C-Job Sparks': 'Войти в C-Job Sparks', 'Create your account': 'Создать аккаунт',
  'Use your approved work account to open your Spark workspace.': 'Используйте подтверждённый рабочий аккаунт, чтобы открыть пространство Sparks.',
  'Request access with your directory email. An administrator must approve it before the first sign-in.': 'Запросите доступ с помощью email из справочника. Перед первым входом запрос должен подтвердить администратор.',
  'Work email': 'Рабочий email', 'Password': 'Пароль', 'Confirm password': 'Подтвердите пароль',
  'Sign in': 'Войти', 'Request access': 'Запросить доступ', 'Need an account?': 'Нужен аккаунт?',
  'Already have access?': 'Уже есть доступ?', 'Try an approved role': 'Попробовать подтверждённую роль',
  'Welcome back': 'С возвращением', 'Local demo access': 'Локальный демо-доступ',
  'Local browser demo · approvals are not shared with other devices · do not use real credentials': 'Локальная браузерная демоверсия · согласования не синхронизируются с другими устройствами · не используйте реальные учётные данные',
  'Skip to account content': 'Перейти к содержимому аккаунта', 'Recognition with purpose': 'Признание со смыслом',
  'Show password': 'Показать пароль', 'Hide password': 'Скрыть пароль',
  'Show passwords': 'Показать пароли', 'Hide passwords': 'Скрыть пароли', 'Please wait…': 'Подождите…',
  'Submit for approval': 'Отправить на согласование', 'Already approved?': 'Доступ уже подтверждён?',
  'Try the approval flow': 'Попробовать процесс согласования', 'Password requirements': 'Требования к паролю',
  '8+ characters': 'Не менее 8 символов', 'Upper & lowercase': 'Прописные и строчные буквы',
  'At least one number': 'Хотя бы одна цифра', 'Met': 'Выполнено', 'Not met': 'Не выполнено',
  'Employee': 'Сотрудник', 'Coordinator': 'Координатор', 'Head': 'Руководитель',
  'Top Management': 'Топ-менеджмент', 'Administrator': 'Администратор',
  'Choose a demo directory profile': 'Выберите демо-профиль из справочника', 'More demo roles': 'Другие демо-роли',
  'No registration in progress': 'Нет активного запроса на регистрацию', 'Access approved': 'Доступ подтверждён',
  'Request needs attention': 'Запрос требует внимания', 'Approval pending': 'Ожидает подтверждения', 'Administrator note': 'Примечание администратора',
  'Activate purchased rewards and keep track of their availability.': 'Активируйте купленные награды и следите за их доступностью.',
  'The reward is now available in your inventory.': 'Награда уже доступна в вашем инвентаре.',
  'Award a Radiant Spark': 'Наградить Radiant Spark', 'Award a Spark': 'Наградить Spark', 'Award details': 'Детали награды',
  'Reward': 'Награда', 'Choose a category': 'Выберите категорию', 'Award date': 'Дата награды',
  'Select an employee': 'Выберите сотрудника', 'Live preview': 'Предпросмотр', 'Award history': 'История наград',
  'Your first award starts here': 'Ваша первая награда начинается здесь',
  'Submitted requests and direct awards will appear here with their current status.': 'Отправленные запросы и прямые награды появятся здесь с текущим статусом.',
  'No people found': 'Сотрудники не найдены', 'Try a different search term.': 'Попробуйте другой поисковый запрос.',
  'Search people': 'Поиск сотрудников', 'Quality Gates': 'Quality Gates', 'Disenchant requests': 'Запросы на распыление',
  'Shop items': 'Товары магазина', 'Add item': 'Добавить товар', 'Adjust Spark balance': 'Изменить баланс Sparks',
  'Recent purchases': 'Последние покупки', 'New item': 'Новый товар', 'Edit item': 'Редактировать товар',
  'Save item': 'Сохранить товар', 'Upload image': 'Загрузить изображение', 'Name': 'Название', 'Description': 'Описание',
  'Manage Spark rules': 'Управлять правилами Sparks', 'No transactions yet': 'Транзакций пока нет',
  'Credits, conversions and disenchant requests for this employee will appear here.': 'Здесь появятся начисления, конвертации и запросы этого сотрудника.',
  'Your work is creating momentum. Here is how it is being recognized.': 'Ваша работа создаёт движение вперёд. Вот как её отмечают.',
  'Every recognition keeps its story, even when the related Sparks are converted or spent.': 'Каждое признание сохраняет свою историю даже после конвертации или расходования Sparks.',
  'Focus mode active': 'Режим фокуса активен', 'VIP active': 'VIP активен', 'Active rewards': 'Активные награды',
  'Synced with My Sparks · Radiant remains permanent': 'Синхронизировано с «Мои Sparks» · Radiant остаётся постоянным',
  'Go to My Sparks': 'Перейти к «Мои Sparks»', 'Reward Shop activity': 'Активность магазина наград',
  'Transactions cannot be edited or deleted.': 'Транзакции нельзя изменить или удалить.',
  'Manual credit': 'Ручное начисление', 'Manual debit': 'Ручное списание',
  'There are no transactions yet.': 'Транзакций пока нет.',
  'Earn twice as many White Sparks from completed activities for 24 hours.': 'Получайте вдвое больше White Sparks за выполненные активности в течение 24 часов.',
  'Protect your current activity streak when you miss one day.': 'Сохраняет текущую серию активности, если вы пропустите один день.',
  'Unlock an exclusive neon theme for your C-Job Sparks workspace.': 'Открывает эксклюзивную неоновую тему рабочего пространства C-Job Sparks.',
  'Add an animated golden frame to your profile avatar.': 'Добавляет анимированную золотую рамку к аватару профиля.',
  'Unlock an exclusive badge for your employee profile.': 'Открывает эксклюзивный значок для профиля сотрудника.',
  'Replace one mission that does not fit your current workload.': 'Позволяет заменить одну миссию, которая не подходит текущей нагрузке.',
  'Receive one random reward of Rare quality or higher.': 'Содержит одну случайную награду редкого или более высокого качества.',
  'Get an exclusive status badge and additional benefits for one week.': 'Даёт эксклюзивный статус, значок и дополнительные преимущества на неделю.',
  'Unlock a distraction-free dashboard mode and keep your active mission highlighted for 24 hours.': 'Включает режим без отвлечений и выделяет активную миссию на 24 часа.',
  'Open a curated reward containing one customization item of Rare quality or higher.': 'Откройте награду с одним предметом персонализации редкого или более высокого качества.',
  'Every credit and debit remains visible. Your balance is calculated from this immutable history.': 'Каждое начисление и списание остаётся видимым. Баланс рассчитывается по этой неизменяемой истории.',
  'Search source or category': 'Поиск по источнику или категории', 'No matching transactions': 'Подходящих транзакций нет',
  'Try a different Spark type, direction or search term.': 'Попробуйте другой тип Spark, направление или поисковый запрос.',
  'No achievements in this view': 'В этом представлении нет достижений',
  'Choose another Spark type to see your recognition history.': 'Выберите другой тип Spark, чтобы увидеть историю признания.',
  'Separate scales': 'Раздельные шкалы', 'No requests yet': 'Запросов пока нет',
  'Your sent nominations and their decisions will appear here.': 'Здесь появятся отправленные номинации и решения по ним.',
  'Confirm Spark conversion': 'Подтвердите конвертацию Sparks', 'Sparks debit immediately': 'Sparks списываются сразу',
  'Request enters accounting': 'Запрос поступает в бухгалтерию', 'Payroll handles payment': 'Выплату обрабатывает бухгалтерия',
  'Recognition should be visible, fair and traceable': 'Признание должно быть видимым, справедливым и отслеживаемым',
  'What each Spark means': 'Что означает каждый Spark', 'Quarterly nominations': 'Квартальные номинации',
  'Who approves each reward': 'Кто согласовывает каждую награду',
  'KPI and personal cards rewards': 'Награды за KPI и персональные карточки',
  'Categories and safeguards': 'Категории и защитные ограничения',
  'What never happens silently': 'Что никогда не происходит незаметно', 'Who appears in each team': 'Кто входит в каждую команду',
  'Prepare a validated batch': 'Подготовьте проверенный пакет', 'Validation sequence': 'Последовательность проверки',
  'Recent system events': 'Последние системные события', 'Administrator invariant': 'Инвариант администратора',
  'Good morning': 'Доброе утро', 'Good afternoon': 'Добрый день', 'Good evening': 'Добрый вечер',
  'Everyday recognition': 'Ежедневное признание', 'Significant contribution': 'Значимый вклад',
  'Long-term impact': 'Долгосрочное влияние', 'Company-wide distinction': 'Признание на уровне компании',
  'achievements received': 'получено достижений', 'categories': 'категории',
  'lifetime achievements': 'достижения за всё время', 'latest KPI': 'последний KPI',
};

const supplementalUk: PhraseMap = {
  'My Sparks': 'Мої Sparks', 'Transaction history': 'Історія транзакцій', 'Search ledger': 'Пошук у реєстрі',
  'All': 'Усі', 'Credit': 'Нарахування', 'Debit': 'Списання',
  'Filter ledger by Spark type': 'Фільтрувати реєстр за типом Spark',
  'Filter ledger by transaction direction': 'Фільтрувати реєстр за напрямком транзакції',
  'Scrollable Spark transaction table': 'Прокручувана таблиця транзакцій Sparks',
  'Swipe sideways to view all transaction details.': 'Проведіть убік, щоб переглянути всі деталі транзакції.',
  'All Spark transactions for the current employee': 'Усі транзакції Sparks поточного працівника',
  'Date': 'Дата', 'Activity': 'Активність', 'Source': 'Джерело', 'Status': 'Статус', 'Details': 'Деталі',
  'Transaction details': 'Деталі транзакції', 'This ledger entry is read-only and cannot be deleted.': 'Цей запис реєстру доступний лише для читання і не може бути видалений.',
  'Transaction ID': 'ID транзакції', 'Date / time': 'Дата / час', 'Transaction type': 'Тип транзакції',
  'Quarter': 'Квартал', 'Employee': 'Працівник', 'Awarded by': 'Нагородив', 'Approved by': 'Погодив',
  'Related request': 'Пов’язаний запит', 'No linked request': 'Немає пов’язаного запиту',
  'Recognize an active Employee, Coordinator or GPM. Approved recognitions create one White Spark and a permanent achievement card.': 'Відзначте активного працівника, координатора або GPM. Погоджене визнання створює один White Spark і постійну картку досягнення.',
  'All fields are required. The Head of Department reviews the contribution.': 'Усі поля обов’язкові. Керівник відділу перевіряє внесок.',
  'Recipient': 'Одержувач', 'Select colleague': 'Виберіть колегу', 'Recognition recipient': 'Одержувач визнання',
  'Select the behaviour to recognize': 'Виберіть поведінку, яку слід відзначити', 'Recognition category': 'Категорія визнання',
  'Reason / description': 'Причина / опис', 'Describe the contribution, context and impact…': 'Опишіть внесок, контекст і вплив…',
  'Example: “Created a deployment checklist that reduced handover errors and saved the project team two hours per release.”': 'Приклад: «Створив чекліст розгортання, який зменшив кількість помилок під час передачі та заощаджує команді проєкту дві години на кожному випуску».',
  'Creates a pending approval request': 'Створює запит на погодження', 'Sending…': 'Надсилання…', 'Send recognition': 'Надіслати визнання',
  'Pending requests reserve a nomination; rejection makes it available again. Unused nominations never roll over to the next quarter.': 'Запити, що очікують, резервують номінацію; відхилення повертає її. Невикористані номінації не переносяться на наступний квартал.',
  'Use this allocation by': 'Використайте квоту до', 'Your requests': 'Ваші запити', 'Pending': 'Очікує', 'Rejected': 'Відхилено',
  'Show less': 'Показати менше', 'Achievement cards preserve the story behind every approved recognition, even after the related Sparks are spent.': 'Картки досягнень зберігають історію кожного погодженого визнання навіть після витрати відповідних Sparks.',
  'Filter achievements by Spark type': 'Фільтрувати досягнення за типом Spark', 'Since your account was created': 'Від часу створення облікового запису',
  'Recognition earned for all time': 'Визнання за весь час',
  'Lifetime earnings count completed recognition credits. Conversion credits are excluded to avoid counting the same value twice, and import corrections are netted automatically.': 'Нагороди за весь час враховують завершені нарахування за визнання. Конвертації виключено, щоб не рахувати ту саму цінність двічі, а коригування імпорту підсумовуються автоматично.',
  'View Spark Ledger': 'Переглянути реєстр Sparks',
  'Performance & automatic rewards': 'Результати й автоматичні нагороди',
  'Scores come from quarterly KPI and Personal Cards results imported and validated by an administrator. White Sparks are awarded from the published score bands after validation; an active Quality Gate blocks the credit.': 'Оцінки формуються з квартальних результатів KPI та персональних карток, які імпортує й перевіряє адміністратор. White Sparks нараховуються за опублікованими діапазонами після перевірки; активний Quality Gate блокує нарахування.',
  'How rewards are calculated': 'Як розраховуються нагороди',
  'KPI: left · Personal Cards: right': 'KPI: ліворуч · Персональні картки: праворуч',
  'Quarterly KPI and personal cards results are imported by Admin. White Sparks are credited after validation and Quality Gate checks.': 'Квартальні KPI та результати персональних карток імпортує адміністратор. White Sparks нараховуються після перевірки й контролю Quality Gate.',
  'No performance data yet': 'Даних про результати ще немає',
  'Validated KPI and Personal Cards results will appear here after the quarterly import.': 'Перевірені результати KPI та персональних карток з’являться тут після квартального імпорту.',
  'Validated KPI and personal cards imports for this employee will appear here. Switch to Administrator and import a sample CSV to try the full workflow.': 'Тут з’являться перевірені імпорти KPI та персональних карток цього працівника. Перейдіть до ролі адміністратора й імпортуйте зразок CSV, щоб перевірити повний процес.',
  'Quarterly performance values': 'Значення квартальних результатів', 'Personal cards': 'Персональні картки',
  'White rewards': 'Нагороди White', 'Not imported': 'Не імпортовано',
  'Build higher-tier Sparks from your available balance. Blue and Radiant Sparks are intentionally not convertible.': 'Створюйте Sparks вищого рівня з доступного балансу. Blue і Radiant навмисно не конвертуються.',
  'Source Spark type': 'Початковий тип Spark', 'Amount to convert': 'Кількість для конвертації', 'available': 'доступно',
  'after confirmation': 'після підтвердження', 'Configured ratio': 'Налаштований курс',
  'Conversion fee (added)': 'Комісія за конвертацію (додається)', 'per complete bundle': 'за повний пакет',
  'Total debit per complete bundle': 'Загальне списання за повний пакет',
  'Review conversion': 'Перевірити конвертацію', 'Safeguards': 'Запобіжники',
  'Convert only complete bundles shown on this page.': 'Конвертуйте лише повні пакети, показані на цій сторінці.',
  'The amount cannot exceed your available balance.': 'Кількість не може перевищувати доступний баланс.',
  'A confirmed conversion is permanent and appears in your Spark Ledger.': 'Підтверджена конвертація є незворотною та з’являється в реєстрі Sparks.',
  'This action creates two permanent Ledger entries.': 'Ця дія створює два постійні записи в реєстрі.',
  'Converting…': 'Конвертація…', 'Confirm conversion': 'Підтвердити конвертацію',
  'Turn eligible Sparks into a monthly payout request. C-Job Sparks prepares accounting data; it does not execute payment.': 'Перетворіть доступні Sparks на щомісячний запит на виплату. C-Job Sparks готує дані для бухгалтерії, але не здійснює оплату.',
  'Radiant Sparks are permanent': 'Radiant Sparks є постійними', 'Permanent': 'Постійний',
  'Calculated according to the current C-Job policy': 'Розраховано відповідно до поточної політики C-Job',
  'Admin can update future operations conditions without changing previous requests.': 'Адміністратор може оновлювати умови майбутніх операцій, не змінюючи попередні запити.',
  'A permanent negative Ledger transaction is created.': 'Створюється постійна від’ємна транзакція в реєстрі.',
  'Your Head sees the amount, rate and period.': 'Ваш керівник бачить суму, курс і період.', 'The application itself never moves money.': 'Застосунок сам не переказує кошти.',
  'Sparks are deducted immediately. The payout is processed later by Accounting.': 'Sparks списуються одразу. Виплату пізніше обробляє бухгалтерія.',
  'Creating…': 'Створення…',
  'What the system is, who can recognize whom, how every Spark is created and what happens after it reaches your account.': 'Що це за система, хто кого може відзначати, як створюється кожен Spark і що відбувається після його надходження на рахунок.',
  'C-Job Sparks turns specific work contributions into a permanent achievement and, when a reward applies, a Ledger transaction. Balances may change through conversion or disenchanting, but the original recognition story is never deleted. It recognizes contribution and behavior; it does not replace salary, bonuses or career progression.': 'C-Job Sparks перетворює конкретний робочий внесок на постійне досягнення і, коли передбачена нагорода, на транзакцію в реєстрі. Баланс може змінюватися через конвертацію чи розпилення, але початкова історія визнання ніколи не видаляється. Система відзначає внесок і поведінку, але не замінює зарплату, бонуси чи кар’єрне зростання.',
  'Four recognition tiers': 'Чотири рівні визнання', 'Everyday peer recognition plus KPI and Personal Cards income.': 'Щоденне визнання від колег, а також нарахування за KPI та Personal Cards.',
  'Significant measurable contribution.': 'Значний вимірюваний внесок.',
  'Prepared a high-quality self-check list that is actively reused by several colleagues. It must be confirmed by relevant self-check lists in the project folder for at least one month.': 'Підготував якісний контрольний список, яким активно користуються кілька колег. Це має бути підтверджено відповідними контрольними списками в папці проєкту протягом щонайменше одного місяця.',
  'Tool or script for one team (project or client team)': 'Інструмент або скрипт для однієї команди (проєктної або клієнтської)',
  'Created and implemented a tool or script for one project team or one client team with proven impact.': 'Створив і впровадив інструмент або скрипт для однієї проєктної чи клієнтської команди з підтвердженим результатом.',
  'Employee of the Year': 'Працівник року',
  'Long-term Automation / Tool / Framework': 'Довгострокова автоматизація / інструмент / фреймворк',
  'Developed an automation, tool or framework with a long-term positive effect across C-Job.': 'Розробив автоматизацію, інструмент або фреймворк із довгостроковим позитивним ефектом для C-Job.',
  'Cross-department System / Process / Toolkit': 'Міжвідділова система / процес / набір інструментів',
  'Created a system, process or toolkit that improves work or efficiency and is used by multiple departments.': 'Створив систему, процес або набір інструментів, що покращує роботу чи ефективність і використовується кількома відділами.',
  'Engineering Standards Contribution': 'Внесок в інженерні стандарти',
  'Made a key contribution to C-Job engineering standards.': 'Зробив ключовий внесок в інженерні стандарти C-Job.',
  'International Conference Representation': 'Представництво на міжнародній конференції',
  'Successfully spoke at an international conference as a C-Job representative.': 'Успішно виступив на міжнародній конференції як представник C-Job.',
  'Most Successful Department Project': 'Найуспішніший проєкт відділу',
  'Coordinated the department’s most successful project of the year, considering savings percentage, total hours, quality and client feedback.': 'Координував найуспішніший проєкт відділу за рік з урахуванням відсотка економії, загальної кількості годин, якості та відгуків клієнта.',
  'Long-term impact with category-specific periods.': 'Довготривалий вплив із періодами для кожної категорії.',
  'Permanent company-wide distinction from Top Management.': 'Постійна відзнака на рівні компанії від топменеджменту.',
  'Clear responsibility': 'Чітка відповідальність', 'Peer recognition, own Sparks, achievements, conversion and disenchant requests.': 'Визнання колег, власні Sparks, досягнення, конвертація та запити на розпилення.',
  'Department team view plus Yellow award requests only for colleagues in a shared active project who have recorded project hours.': 'Перегляд команди відділу та запити на нагороди Yellow лише для колег зі спільного активного проєкту, які мають обліковані години в ньому.',
  'Company-wide team view and White/Yellow award requests. GPM White allocation is based on active Coordinators and registrars under their control.': 'Перегляд команди всієї компанії та запити на нагороди White/Yellow. Квота GPM на White залежить від активних координаторів і реєстраторів під його керуванням.',
  'Department approvals, direct White/Yellow/Blue awards, Quality Gates and the monthly Accounting list.': 'Погодження відділу, прямі нагороди White/Yellow/Blue, Quality Gates і щомісячний список для бухгалтерії.',
  'Company-wide Radiant awards.': 'Нагороди Radiant на рівні компанії.', 'Directory, imports and rules; administrative access alone gives no award rights.': 'Довідник, імпорти й правила; сам адміністративний доступ не дає права нагороджувати.',
  'From nomination to history': 'Від номінації до історії',
  'The recipient’s Head approves or rejects it. Approval credits 1 White; rejection returns the nomination.': 'Керівник одержувача погоджує або відхиляє запит. Погодження нараховує 1 White, а відхилення повертає номінацію.',
  'Coordinator Yellow and GPM White/Yellow awards': 'Нагороди Yellow від координатора та White/Yellow від GPM', 'They remain Pending until the recipient’s Head approves them. Rejections always include a reason.': 'Вони залишаються в очікуванні, доки керівник одержувача їх не погодить. Відхилення завжди містить причину.',
  'Head awards': 'Нагороди керівника', 'White, Yellow and Blue are awarded directly after all limits, duplicate rules and Quality Gates pass.': 'White, Yellow і Blue нараховуються безпосередньо після проходження всіх лімітів, перевірок дублів і Quality Gates.',
  'Top Management awards': 'Нагороди топменеджменту', 'Radiant is awarded directly and never requires an additional approval.': 'Radiant нараховується безпосередньо й не потребує додаткового погодження.',
  'Automatic White Sparks': 'Автоматичні White Sparks', 'KPI thresholds': 'Пороги KPI', 'Personal cards thresholds': 'Пороги персональних карток',
  'Quarterly import': 'Квартальний імпорт', 'Admin previews and validates one result per employee, source and quarter before confirming it.': 'Адміністратор попередньо переглядає та перевіряє один результат на працівника, джерело й квартал перед підтвердженням.',
  'Corrections and Quality Gates': 'Коригування та Quality Gates', 'A replacement creates correction entries instead of duplicates. An active Quality Gate blocks the White credit.': 'Заміна створює записи коригування замість дублів. Активний Quality Gate блокує нарахування White.',
  'Awards': 'Нагороди', 'active categories': 'активних категорій', 'Blue award grounds': 'Підстави для нагороди Blue', 'Additional conversion fee': 'Додаткова комісія за конвертацію',
  'source Spark per bundle': 'початковий Spark за пакет', 'Quality and history': 'Якість та історія', 'Team scope': 'Склад команди',
  'Pending requests reserve a nomination. Rejection releases it.': 'Запити, що очікують, резервують номінацію. Відхилення повертає її.',
  'The recipient’s Head approves or rejects the request. A rejection always includes a reason.': 'Керівник одержувача погоджує або відхиляє запит. Відхилення завжди містить причину.',
  'The sender must fill in all required details during Peer recognition, including the work, the contribution and why it deserves recognition.': 'Під час Peer recognition відправник має заповнити всі обов’язкові дані, зокрема описати роботу, внесок і причину, чому він заслуговує на визнання.',
  'Direct Yellow awards and pending Yellow requests together cannot exceed': 'Прямі нагороди Yellow і запити Yellow, що очікують, разом не можуть перевищувати',
  'per employee per quarter': 'на працівника за квартал',
  'There is no issuer limit on the number of awards or recipients.': 'Кількість нагород або одержувачів для автора не обмежена.',
  'An award that would exceed the 7 Yellow limit is blocked in full and is never reduced automatically.': 'Нагорода, що перевищує ліміт у 7 Yellow, блокується повністю й ніколи не зменшується автоматично.',
  'The first acting coordinator or lead category is unavailable after coordination experience is recorded.': 'Категорія першого виконання обов’язків координатора або керівника недоступна після фіксації досвіду координації.',
  'Yellow requests require a specific achievement description before they can be submitted.': 'Запити Yellow потребують конкретного опису досягнення перед надсиланням.',
  'A GPM may request White awards: 1 for 1–3 active Coordinators or registrars under their control, 2 for 4–6, and one additional White for each next group of 3.': 'GPM може запитувати нагороди White: 1 за 1–3 активних координаторів або реєстраторів під своїм керуванням, 2 за 4–6 і ще одну White за кожну наступну групу з 3.',
  'Blue is awarded only by a Head. The same category cannot repeat for one employee during its configured quarterly, yearly or one-time period.': 'Blue нараховує лише керівник. Та сама категорія не може повторюватися для одного працівника протягом налаштованого квартального, річного або одноразового періоду.',
  'Employee of the Year has an annual department quota of floor(active employees ÷ 10).': '«Працівник року» має річну квоту відділу: ціла частина від кількості активних працівників, поділеної на 10.',
  'Radiant has no fixed categories.': 'Radiant не має фіксованих категорій.',
  'Top Management chooses an employee, enters a required reason and description, and awards exactly 1 Radiant directly. It is permanent and needs no approval.': 'Топменеджмент обирає працівника, вводить обов’язкові причину й опис і безпосередньо нараховує рівно 1 Radiant. Він постійний і не потребує погодження.',
  'Radiant is permanent: it cannot be converted, spent or disenchanted.': 'Radiant є постійним: його не можна конвертувати, витратити або розпилити.',
  'Blue cannot be converted. Only White and Yellow can be converted to the next tier.': 'Blue не можна конвертувати. Лише White і Yellow можна конвертувати в наступний рівень.',
  'Submitting a disenchant request debits the selected Sparks immediately and creates a request.': 'Надсилання запиту на розпилення одразу списує вибрані Sparks і створює запит.',
  'The Head compiles the monthly request list and sends it to Accounting; the system never pays automatically.': 'Керівник формує щомісячний список запитів і надсилає його до бухгалтерії; система ніколи не здійснює виплату автоматично.',
  'An active Quality Gate blocks all positive White sources during its stated dates: KPI, Personal Cards, Peer Recognition, direct/manual awards and adjustments.': 'Активний Quality Gate протягом зазначених дат блокує всі позитивні джерела White: KPI, персональні картки, визнання колег, прямі або ручні нагороди й коригування.',
  'Yellow, Blue and Radiant awards are not blocked by a Quality Gate.': 'Нагороди Yellow, Blue і Radiant не блокуються Quality Gate.',
  'Every balance-changing operation creates a read-only Ledger entry.': 'Кожна операція, що змінює баланс, створює запис реєстру лише для читання.',
  'Achievements remain visible after Sparks are converted or disenchanted.': 'Досягнення залишаються видимими після конвертації або розпилення Sparks.',
  'Import replacements add correction entries; existing history is not overwritten.': 'Заміни імпорту додають коригувальні записи; наявна історія не перезаписується.',
  'A Coordinator sees active colleagues from their own department.': 'Координатор бачить активних колег зі свого відділу.',
  'A Coordinator can award only colleagues in a shared active project team who have recorded hours on that project.': 'Координатор може нагороджувати лише колег зі спільної активної проєктної команди, які мають обліковані години в цьому проєкті.',
  'A GPM sees active colleagues across the whole company.': 'GPM бачить активних колег у всій компанії.',
  'A Head works with their own department and can see the balances needed for management.': 'Керівник працює зі своїм відділом і бачить баланси, потрібні для керування.',
  'Coordinator and GPM team cards keep colleague balances private.': 'Картки команди координатора та GPM не показують баланси колег.',
  'Every colleague card links directly to Peer recognition with that person already selected.': 'Кожна картка колеги веде безпосередньо до визнання колег із уже вибраною людиною.',
  'Every business role starts with': 'Кожна бізнес-роль починає з', 'peer nomination per quarter.': 'номінації колеги на квартал.',
  'A Coordinator receives one extra nomination for every': 'Координатор отримує одну додаткову номінацію на кожні',
  'active colleagues in their project team(s).': 'активних колег у своїй проєктній команді або командах.',
  'Recipients are active Employees, Coordinators or GPMs; self-recognition is blocked.': 'Одержувачами можуть бути активні працівники, координатори або GPM; самовизнання заблоковано.',
  'Unused peer recognition expires on the last day of each quarter.': 'Невикористані можливості Peer recognition спливають в останній день кожного кварталу.',
  'Yellow awards are available only for colleagues in a shared active project with recorded hours, then submitted to the recipient’s Head.': 'Нагороди Yellow доступні лише для колег зі спільного активного проєкту з облікованими годинами, після чого запит надсилається керівнику одержувача.',
  'White and Yellow awards are submitted to the recipient’s Head. White allocation is based on the Coordinators and registrars under your control.': 'Запити на нагороди White і Yellow надсилаються керівнику одержувача. Квота White залежить від координаторів і реєстраторів під вашим керуванням.',
  'Quarterly allocation': 'Квартальна квота', 'GPM White awards': 'Нагороди White від GPM',
  'Awarded or reserved': 'Нараховано або зарезервовано',
  'The same Yellow category cannot be used twice in that quarter. White credits, converted Yellow, Blue and Radiant do not use this limit.': 'Ту саму категорію Yellow не можна використати двічі в одному кварталі. Нарахування White, конвертовані Yellow, Blue і Radiant не використовують цей ліміт.',
  'base value →': 'базова вартість →',
  'Preparing demo access': 'Підготовка демо-доступу', 'Account status and permissions are loading.': 'Завантажуються стан облікового запису та дозволи.',
  'Sign-in unavailable': 'Вхід недоступний', 'Permission-aware route': 'Маршрут із перевіркою дозволів',
  'Your account role': 'Ваша роль', 'cannot open': 'не може відкрити',
  'Contact an administrator if your employee-directory role needs to be updated.': 'Зверніться до адміністратора, якщо роль у довіднику працівників потрібно оновити.',
  'Back to dashboard': 'Повернутися на головну',
  'Head scope': 'Область керівника', 'GPM scope': 'Область GPM', 'Coordinator scope': 'Область координатора',
  'Department workspace': 'Робочий простір відділу', 'Department team': 'Команда відділу', 'Company team': 'Команда компанії',
  'Department balances, Quality Gates and accounting requests, with a complete audit trail.': 'Баланси відділу, Quality Gates і бухгалтерські запити з повною історією аудиту.',
  'Find any active colleague across C-Job. Spark balances remain private.': 'Знайдіть будь-якого активного колегу в C-Job. Баланси Sparks залишаються приватними.',
  'Work with active colleagues in your department. Spark balances remain private.': 'Працюйте з активними колегами свого відділу. Баланси Sparks залишаються приватними.',
  'Available': 'Доступний', 'Blocked': 'Заблоковано', 'Scheduled': 'Заплановано', 'Cancelled': 'Скасовано',
  'Spark balance stays private for this role.': 'Баланс Sparks залишається приватним для цієї ролі.',
  'No active Quality Gate': 'Немає активного Quality Gate', 'Set gate': 'Установити обмеження', 'Cancel gate': 'Скасувати обмеження',
  'Department quality history': 'Історія якості відділу', 'No Quality Gates': 'Quality Gates відсутні',
  'Set a gate from an employee card when a documented remediation period is needed.': 'Установіть обмеження в картці працівника, коли потрібен задокументований період виправлення.',
  'Scrollable Quality Gate history': 'Прокручувана історія Quality Gate', 'Department Quality Gate history': 'Історія Quality Gate відділу',
  'Period': 'Період', 'Reason': 'Причина', 'Request': 'Запит', 'Sparks': 'Sparks', 'Rate': 'Ставка', 'Money value': 'Грошова вартість',
  'No accounting requests yet': 'Бухгалтерських запитів ще немає',
  'Disenchant requests from employees in this department will appear here. This frontend does not send payments.': 'Тут з’являться запити на розпилення від працівників цього відділу. Цей frontend не здійснює виплати.',
  'Scrollable accounting requests': 'Прокручувані бухгалтерські запити', 'Department disenchant requests for accounting': 'Запити відділу на розпилення для бухгалтерії',
  'Quality Gate saved. White credits are blocked only during its active dates.': 'Quality Gate збережено. Нарахування White заблоковано лише протягом активних дат.',
  'Quality Gate cancelled.': 'Quality Gate скасовано.',
};

const supplementalRu: PhraseMap = {
  'My Sparks': 'Мои Sparks', 'Transaction history': 'История транзакций', 'Search ledger': 'Поиск по реестру',
  'All': 'Все', 'Credit': 'Начисление', 'Debit': 'Списание',
  'Filter ledger by Spark type': 'Фильтровать реестр по типу Spark', 'Filter ledger by transaction direction': 'Фильтровать реестр по направлению транзакции',
  'Scrollable Spark transaction table': 'Прокручиваемая таблица транзакций Sparks', 'All Spark transactions for the current employee': 'Все транзакции Sparks текущего сотрудника',
  'Swipe sideways to view all transaction details.': 'Проведите в сторону, чтобы увидеть все детали транзакции.',
  'Date': 'Дата', 'Activity': 'Активность', 'Source': 'Источник', 'Status': 'Статус', 'Details': 'Детали',
  'Transaction details': 'Детали транзакции', 'This ledger entry is read-only and cannot be deleted.': 'Эта запись реестра доступна только для чтения и не может быть удалена.',
  'Transaction ID': 'ID транзакции', 'Date / time': 'Дата / время', 'Transaction type': 'Тип транзакции', 'Quarter': 'Квартал',
  'Employee': 'Сотрудник', 'Awarded by': 'Наградил', 'Approved by': 'Согласовал', 'Related request': 'Связанный запрос', 'No linked request': 'Нет связанного запроса',
  'Recognize an active Employee, Coordinator or GPM. Approved recognitions create one White Spark and a permanent achievement card.': 'Отметьте активного сотрудника, координатора или GPM. Согласованное признание создаёт один White Spark и постоянную карточку достижения.',
  'All fields are required. The Head of Department reviews the contribution.': 'Все поля обязательны. Руководитель отдела проверяет вклад.',
  'Recipient': 'Получатель', 'Select colleague': 'Выберите коллегу', 'Recognition recipient': 'Получатель признания',
  'Select the behaviour to recognize': 'Выберите поведение, которое нужно отметить', 'Recognition category': 'Категория признания',
  'Reason / description': 'Причина / описание', 'Describe the contribution, context and impact…': 'Опишите вклад, контекст и влияние…',
  'Example: “Created a deployment checklist that reduced handover errors and saved the project team two hours per release.”': 'Пример: «Создал чек-лист развёртывания, который сократил ошибки при передаче и экономит команде проекта два часа на каждом выпуске».',
  'Creates a pending approval request': 'Создаёт запрос на согласование', 'Sending…': 'Отправка…', 'Send recognition': 'Отправить признание',
  'Pending requests reserve a nomination; rejection makes it available again. Unused nominations never roll over to the next quarter.': 'Ожидающие запросы резервируют номинацию; отклонение возвращает её. Неиспользованные номинации не переносятся на следующий квартал.',
  'Use this allocation by': 'Используйте квоту до', 'Your requests': 'Ваши запросы', 'Pending': 'Ожидает', 'Rejected': 'Отклонено', 'Show less': 'Показать меньше',
  'Achievement cards preserve the story behind every approved recognition, even after the related Sparks are spent.': 'Карточки достижений сохраняют историю каждого согласованного признания даже после расходования соответствующих Sparks.',
  'Filter achievements by Spark type': 'Фильтровать достижения по типу Spark', 'Since your account was created': 'С момента создания аккаунта',
  'Recognition earned for all time': 'Признание за всё время',
  'Lifetime earnings count completed recognition credits. Conversion credits are excluded to avoid counting the same value twice, and import corrections are netted automatically.': 'Награды за всё время учитывают завершённые начисления за признание. Конвертации исключены, чтобы не считать одну ценность дважды, а исправления импорта суммируются автоматически.',
  'View Spark Ledger': 'Открыть реестр Sparks',
  'Performance & automatic rewards': 'Результаты и автоматические награды',
  'Scores come from quarterly KPI and Personal Cards results imported and validated by an administrator. White Sparks are awarded from the published score bands after validation; an active Quality Gate blocks the credit.': 'Оценки формируются из квартальных результатов KPI и персональных карточек, которые импортирует и проверяет администратор. White Sparks начисляются по опубликованным диапазонам после проверки; активный Quality Gate блокирует начисление.',
  'How rewards are calculated': 'Как рассчитываются награды',
  'KPI: left · Personal Cards: right': 'KPI: слева · Персональные карточки: справа',
  'Quarterly KPI and personal cards results are imported by Admin. White Sparks are credited after validation and Quality Gate checks.': 'Квартальные KPI и результаты персональных карточек импортирует администратор. White Sparks начисляются после проверки и контроля Quality Gate.',
  'No performance data yet': 'Данных о результатах пока нет',
  'Validated KPI and Personal Cards results will appear here after the quarterly import.': 'Проверенные результаты KPI и персональных карточек появятся здесь после квартального импорта.',
  'Validated KPI and personal cards imports for this employee will appear here. Switch to Administrator and import a sample CSV to try the full workflow.': 'Здесь появятся проверенные импорты KPI и персональных карточек этого сотрудника. Переключитесь на администратора и импортируйте образец CSV, чтобы проверить весь процесс.',
  'Quarterly performance values': 'Значения квартальных результатов', 'Personal cards': 'Персональные карточки', 'White rewards': 'Награды White', 'Not imported': 'Не импортировано',
  'Build higher-tier Sparks from your available balance. Blue and Radiant Sparks are intentionally not convertible.': 'Создавайте Sparks более высокого уровня из доступного баланса. Blue и Radiant намеренно не конвертируются.',
  'Source Spark type': 'Исходный тип Spark', 'Amount to convert': 'Количество для конвертации', 'available': 'доступно', 'after confirmation': 'после подтверждения',
  'Configured ratio': 'Настроенный курс', 'Conversion fee (added)': 'Комиссия за конвертацию (добавляется)', 'per complete bundle': 'за полный пакет',
  'Total debit per complete bundle': 'Общее списание за полный пакет',
  'Review conversion': 'Проверить конвертацию', 'Safeguards': 'Ограничения',
  'Convert only complete bundles shown on this page.': 'Конвертируйте только полные пакеты, показанные на этой странице.',
  'The amount cannot exceed your available balance.': 'Количество не может превышать доступный баланс.',
  'A confirmed conversion is permanent and appears in your Spark Ledger.': 'Подтверждённая конвертация необратима и появляется в реестре Sparks.',
  'This action creates two permanent Ledger entries.': 'Это действие создаёт две постоянные записи в реестре.', 'Converting…': 'Конвертация…', 'Confirm conversion': 'Подтвердить конвертацию',
  'Turn eligible Sparks into a monthly payout request. C-Job Sparks prepares accounting data; it does not execute payment.': 'Преобразуйте доступные Sparks в ежемесячный запрос на выплату. C-Job Sparks готовит данные для бухгалтерии, но не выполняет платёж.',
  'Radiant Sparks are permanent': 'Radiant Sparks являются постоянными', 'Permanent': 'Постоянный',
  'Calculated according to the current C-Job policy': 'Рассчитано согласно текущей политике C-Job',
  'Admin can update future operations conditions without changing previous requests.': 'Администратор может обновлять условия будущих операций, не изменяя предыдущие запросы.',
  'A permanent negative Ledger transaction is created.': 'Создаётся постоянная отрицательная транзакция в реестре.', 'Your Head sees the amount, rate and period.': 'Ваш руководитель видит сумму, курс и период.',
  'The application itself never moves money.': 'Приложение само не переводит деньги.', 'Sparks are deducted immediately. The payout is processed later by Accounting.': 'Sparks списываются сразу. Выплату позже обрабатывает бухгалтерия.',
  'Creating…': 'Создание…',
  'What the system is, who can recognize whom, how every Spark is created and what happens after it reaches your account.': 'Что это за система, кто кого может отмечать, как создаётся каждый Spark и что происходит после его поступления на счёт.',
  'C-Job Sparks turns specific work contributions into a permanent achievement and, when a reward applies, a Ledger transaction. Balances may change through conversion or disenchanting, but the original recognition story is never deleted. It recognizes contribution and behavior; it does not replace salary, bonuses or career progression.': 'C-Job Sparks превращает конкретный рабочий вклад в постоянное достижение и, когда предусмотрена награда, в транзакцию реестра. Баланс может меняться из-за конвертации или распыления, но исходная история признания никогда не удаляется. Система отмечает вклад и поведение, но не заменяет зарплату, бонусы или карьерный рост.',
  'Four recognition tiers': 'Четыре уровня признания', 'Everyday peer recognition plus KPI and Personal Cards income.': 'Ежедневное признание от коллег, а также начисления за KPI и Personal Cards.',
  'Significant measurable contribution.': 'Значительный измеримый вклад.', 'Long-term impact with category-specific periods.': 'Долгосрочное влияние с периодами для каждой категории.',
  'Prepared a high-quality self-check list that is actively reused by several colleagues. It must be confirmed by relevant self-check lists in the project folder for at least one month.': 'Подготовил качественный контрольный список, которым активно пользуются несколько коллег. Это должно быть подтверждено соответствующими контрольными списками в папке проекта на протяжении как минимум одного месяца.',
  'Tool or script for one team (project or client team)': 'Инструмент или скрипт для одной команды (проектной или клиентской)',
  'Created and implemented a tool or script for one project team or one client team with proven impact.': 'Создал и внедрил инструмент или скрипт для одной проектной или клиентской команды с подтверждённым результатом.',
  'Employee of the Year': 'Сотрудник года',
  'Long-term Automation / Tool / Framework': 'Долгосрочная автоматизация / инструмент / фреймворк',
  'Developed an automation, tool or framework with a long-term positive effect across C-Job.': 'Разработал автоматизацию, инструмент или фреймворк с долгосрочным положительным эффектом для C-Job.',
  'Cross-department System / Process / Toolkit': 'Межотдельная система / процесс / набор инструментов',
  'Created a system, process or toolkit that improves work or efficiency and is used by multiple departments.': 'Создал систему, процесс или набор инструментов, улучшающий работу или эффективность и используемый несколькими отделами.',
  'Engineering Standards Contribution': 'Вклад в инженерные стандарты',
  'Made a key contribution to C-Job engineering standards.': 'Внёс ключевой вклад в инженерные стандарты C-Job.',
  'International Conference Representation': 'Представительство на международной конференции',
  'Successfully spoke at an international conference as a C-Job representative.': 'Успешно выступил на международной конференции как представитель C-Job.',
  'Most Successful Department Project': 'Самый успешный проект отдела',
  'Coordinated the department’s most successful project of the year, considering savings percentage, total hours, quality and client feedback.': 'Координировал самый успешный проект отдела за год с учётом процента экономии, общего количества часов, качества и отзывов клиента.',
  'Permanent company-wide distinction from Top Management.': 'Постоянное признание на уровне компании от топ-менеджмента.', 'Clear responsibility': 'Чёткая ответственность',
  'Peer recognition, own Sparks, achievements, conversion and disenchant requests.': 'Признание коллег, собственные Sparks, достижения, конвертация и запросы на распыление.',
  'Department team view plus Yellow award requests only for colleagues in a shared active project who have recorded project hours.': 'Просмотр команды отдела и запросы на награды Yellow только для коллег из общего активного проекта с учтёнными проектными часами.',
  'Company-wide team view and White/Yellow award requests. GPM White allocation is based on active Coordinators and registrars under their control.': 'Просмотр команды всей компании и запросы на награды White/Yellow. Квота GPM на White зависит от активных координаторов и регистраторов под его управлением.',
  'Department approvals, direct White/Yellow/Blue awards, Quality Gates and the monthly Accounting list.': 'Согласования отдела, прямые награды White/Yellow/Blue, Quality Gates и ежемесячный список для бухгалтерии.',
  'Company-wide Radiant awards.': 'Награды Radiant на уровне компании.', 'Directory, imports and rules; administrative access alone gives no award rights.': 'Справочник, импорты и правила; один административный доступ не даёт права награждать.',
  'From nomination to history': 'От номинации к истории', 'The recipient’s Head approves or rejects it. Approval credits 1 White; rejection returns the nomination.': 'Руководитель получателя согласовывает или отклоняет запрос. Согласование начисляет 1 White, а отклонение возвращает номинацию.',
  'Coordinator Yellow and GPM White/Yellow awards': 'Награды Yellow от координатора и White/Yellow от GPM', 'They remain Pending until the recipient’s Head approves them. Rejections always include a reason.': 'Они остаются в ожидании, пока руководитель получателя их не согласует. Отклонение всегда содержит причину.',
  'Head awards': 'Награды руководителя', 'White, Yellow and Blue are awarded directly after all limits, duplicate rules and Quality Gates pass.': 'White, Yellow и Blue начисляются напрямую после прохождения всех лимитов, проверок дублей и Quality Gates.',
  'Top Management awards': 'Награды топ-менеджмента', 'Radiant is awarded directly and never requires an additional approval.': 'Radiant начисляется напрямую и никогда не требует дополнительного согласования.',
  'Automatic White Sparks': 'Автоматические White Sparks', 'KPI thresholds': 'Пороги KPI', 'Personal cards thresholds': 'Пороги персональных карточек',
  'Quarterly import': 'Квартальный импорт', 'Admin previews and validates one result per employee, source and quarter before confirming it.': 'Администратор предварительно просматривает и проверяет один результат на сотрудника, источник и квартал перед подтверждением.',
  'Corrections and Quality Gates': 'Исправления и Quality Gates', 'A replacement creates correction entries instead of duplicates. An active Quality Gate blocks the White credit.': 'Замена создаёт корректирующие записи вместо дублей. Активный Quality Gate блокирует начисление White.',
  'Awards': 'Награды', 'active categories': 'активных категорий', 'Blue award grounds': 'Основания для награды Blue', 'Additional conversion fee': 'Дополнительная комиссия за конвертацию',
  'source Spark per bundle': 'исходный Spark за пакет',
  'Quality and history': 'Качество и история', 'Team scope': 'Состав команды',
  'Pending requests reserve a nomination. Rejection releases it.': 'Ожидающие запросы резервируют номинацию. Отклонение возвращает её.',
  'The recipient’s Head approves or rejects the request. A rejection always includes a reason.': 'Руководитель получателя согласовывает или отклоняет запрос. Отклонение всегда содержит причину.',
  'The sender must fill in all required details during Peer recognition, including the work, the contribution and why it deserves recognition.': 'Во время Peer recognition отправитель должен заполнить все обязательные данные, включая описание работы, вклада и причины, почему он заслуживает признания.',
  'Direct Yellow awards and pending Yellow requests together cannot exceed': 'Прямые награды Yellow и ожидающие запросы Yellow вместе не могут превышать',
  'per employee per quarter': 'на сотрудника за квартал',
  'There is no issuer limit on the number of awards or recipients.': 'Количество наград или получателей для автора не ограничено.',
  'An award that would exceed the 7 Yellow limit is blocked in full and is never reduced automatically.': 'Награда, превышающая лимит в 7 Yellow, блокируется полностью и никогда не уменьшается автоматически.',
  'The first acting coordinator or lead category is unavailable after coordination experience is recorded.': 'Категория первого исполнения обязанностей координатора или руководителя недоступна после фиксации опыта координации.',
  'Yellow requests require a specific achievement description before they can be submitted.': 'Запросы Yellow требуют конкретного описания достижения перед отправкой.',
  'A GPM may request White awards: 1 for 1–3 active Coordinators or registrars under their control, 2 for 4–6, and one additional White for each next group of 3.': 'GPM может запрашивать награды White: 1 за 1–3 активных координаторов или регистраторов под своим управлением, 2 за 4–6 и ещё одну White за каждую следующую группу из 3.',
  'Blue is awarded only by a Head. The same category cannot repeat for one employee during its configured quarterly, yearly or one-time period.': 'Blue начисляет только руководитель. Одна категория не может повторяться для сотрудника в течение настроенного квартального, годового или одноразового периода.',
  'Employee of the Year has an annual department quota of floor(active employees ÷ 10).': '«Сотрудник года» имеет годовую квоту отдела: целая часть от количества активных сотрудников, делённого на 10.',
  'Radiant has no fixed categories.': 'Radiant не имеет фиксированных категорий.',
  'Top Management chooses an employee, enters a required reason and description, and awards exactly 1 Radiant directly. It is permanent and needs no approval.': 'Топ-менеджмент выбирает сотрудника, вводит обязательные причину и описание и напрямую начисляет ровно 1 Radiant. Он постоянный и не требует согласования.',
  'Radiant is permanent: it cannot be converted, spent or disenchanted.': 'Radiant является постоянным: его нельзя конвертировать, потратить или распылить.',
  'Blue cannot be converted. Only White and Yellow can be converted to the next tier.': 'Blue нельзя конвертировать. Только White и Yellow можно конвертировать в следующий уровень.',
  'Submitting a disenchant request debits the selected Sparks immediately and creates a request.': 'Отправка запроса на распыление сразу списывает выбранные Sparks и создаёт запрос.',
  'The Head compiles the monthly request list and sends it to Accounting; the system never pays automatically.': 'Руководитель формирует ежемесячный список запросов и отправляет его в бухгалтерию; система никогда не выполняет выплату автоматически.',
  'An active Quality Gate blocks all positive White sources during its stated dates: KPI, Personal Cards, Peer Recognition, direct/manual awards and adjustments.': 'Активный Quality Gate в указанные даты блокирует все положительные источники White: KPI, персональные карточки, признание коллег, прямые или ручные награды и корректировки.',
  'Yellow, Blue and Radiant awards are not blocked by a Quality Gate.': 'Награды Yellow, Blue и Radiant не блокируются Quality Gate.',
  'Every balance-changing operation creates a read-only Ledger entry.': 'Каждая операция, меняющая баланс, создаёт запись реестра только для чтения.',
  'Achievements remain visible after Sparks are converted or disenchanted.': 'Достижения остаются видимыми после конвертации или распыления Sparks.',
  'Import replacements add correction entries; existing history is not overwritten.': 'Замены импорта добавляют корректирующие записи; существующая история не перезаписывается.',
  'A Coordinator sees active colleagues from their own department.': 'Координатор видит активных коллег из своего отдела.',
  'A Coordinator can award only colleagues in a shared active project team who have recorded hours on that project.': 'Координатор может награждать только коллег из общей активной проектной команды, у которых учтены часы в этом проекте.',
  'A GPM sees active colleagues across the whole company.': 'GPM видит активных коллег по всей компании.',
  'A Head works with their own department and can see the balances needed for management.': 'Руководитель работает со своим отделом и видит балансы, необходимые для управления.',
  'Coordinator and GPM team cards keep colleague balances private.': 'Карточки команды координатора и GPM скрывают балансы коллег.',
  'Every colleague card links directly to Peer recognition with that person already selected.': 'Каждая карточка коллеги ведёт прямо к признанию коллег с уже выбранным человеком.',
  'Every business role starts with': 'Каждая бизнес-роль начинает с', 'peer nomination per quarter.': 'номинации коллеги на квартал.',
  'A Coordinator receives one extra nomination for every': 'Координатор получает одну дополнительную номинацию на каждые',
  'active colleagues in their project team(s).': 'активных коллег в своей проектной команде или командах.',
  'Recipients are active Employees, Coordinators or GPMs; self-recognition is blocked.': 'Получателями могут быть активные сотрудники, координаторы или GPM; самопризнание заблокировано.',
  'Unused peer recognition expires on the last day of each quarter.': 'Неиспользованные возможности Peer recognition истекают в последний день каждого квартала.',
  'Yellow awards are available only for colleagues in a shared active project with recorded hours, then submitted to the recipient’s Head.': 'Награды Yellow доступны только для коллег из общего активного проекта с учтёнными часами, после чего запрос отправляется руководителю получателя.',
  'White and Yellow awards are submitted to the recipient’s Head. White allocation is based on the Coordinators and registrars under your control.': 'Запросы на награды White и Yellow отправляются руководителю получателя. Квота White зависит от координаторов и регистраторов под вашим управлением.',
  'Quarterly allocation': 'Квартальная квота', 'GPM White awards': 'Награды White от GPM',
  'Awarded or reserved': 'Начислено или зарезервировано',
  'The same Yellow category cannot be used twice in that quarter. White credits, converted Yellow, Blue and Radiant do not use this limit.': 'Одну категорию Yellow нельзя использовать дважды в одном квартале. Начисления White, конвертированные Yellow, Blue и Radiant не используют этот лимит.',
  'base value →': 'базовая стоимость →',
  'Preparing demo access': 'Подготовка демо-доступа', 'Account status and permissions are loading.': 'Загружаются состояние аккаунта и разрешения.',
  'Sign-in unavailable': 'Вход недоступен', 'Permission-aware route': 'Маршрут с проверкой разрешений',
  'Your account role': 'Ваша роль', 'cannot open': 'не может открыть',
  'Contact an administrator if your employee-directory role needs to be updated.': 'Обратитесь к администратору, если роль в справочнике сотрудников нужно обновить.',
  'Back to dashboard': 'Вернуться на главную',
  'Head scope': 'Область руководителя', 'GPM scope': 'Область GPM', 'Coordinator scope': 'Область координатора',
  'Department workspace': 'Рабочее пространство отдела', 'Department team': 'Команда отдела', 'Company team': 'Команда компании',
  'Department balances, Quality Gates and accounting requests, with a complete audit trail.': 'Балансы отдела, Quality Gates и бухгалтерские запросы с полной историей аудита.',
  'Find any active colleague across C-Job. Spark balances remain private.': 'Найдите любого активного коллегу в C-Job. Балансы Sparks остаются приватными.',
  'Work with active colleagues in your department. Spark balances remain private.': 'Работайте с активными коллегами своего отдела. Балансы Sparks остаются приватными.',
  'Available': 'Доступен', 'Blocked': 'Заблокировано', 'Scheduled': 'Запланировано', 'Cancelled': 'Отменено',
  'Spark balance stays private for this role.': 'Баланс Sparks остаётся приватным для этой роли.',
  'No active Quality Gate': 'Нет активного Quality Gate', 'Set gate': 'Установить ограничение', 'Cancel gate': 'Отменить ограничение',
  'Department quality history': 'История качества отдела', 'No Quality Gates': 'Quality Gates отсутствуют',
  'Set a gate from an employee card when a documented remediation period is needed.': 'Установите ограничение в карточке сотрудника, когда требуется документированный период исправления.',
  'Scrollable Quality Gate history': 'Прокручиваемая история Quality Gate', 'Department Quality Gate history': 'История Quality Gate отдела',
  'Period': 'Период', 'Reason': 'Причина', 'Request': 'Запрос', 'Sparks': 'Sparks', 'Rate': 'Ставка', 'Money value': 'Денежная стоимость',
  'No accounting requests yet': 'Бухгалтерских запросов пока нет',
  'Disenchant requests from employees in this department will appear here. This frontend does not send payments.': 'Здесь появятся запросы на распыление от сотрудников этого отдела. Этот frontend не выполняет выплаты.',
  'Scrollable accounting requests': 'Прокручиваемые бухгалтерские запросы', 'Department disenchant requests for accounting': 'Запросы отдела на распыление для бухгалтерии',
  'Quality Gate saved. White credits are blocked only during its active dates.': 'Quality Gate сохранён. Начисления White блокируются только в течение активных дат.',
  'Quality Gate cancelled.': 'Quality Gate отменён.',
};

const maps: Record<Exclude<InterfaceLanguage, 'en'>, PhraseMap> = {
  uk: { ...uk, ...supplementalUk },
  ru: { ...ru, ...supplementalRu },
};

const dynamic = (language: Exclude<InterfaceLanguage, 'en'>, value: string) => {
  const greeting = value.match(/^Good (morning|afternoon|evening), (.+)\.$/);
  if (greeting) {
    const prefix = language === 'uk'
      ? ({ morning: 'Доброго ранку', afternoon: 'Добрий день', evening: 'Добрий вечір' } as const)[greeting[1] as 'morning']
      : ({ morning: 'Доброе утро', afternoon: 'Добрый день', evening: 'Добрый вечер' } as const)[greeting[1] as 'morning'];
    return `${prefix}, ${greeting[2]}.`;
  }
  const available = value.match(/^(\d+) (White|Yellow|Blue) Sparks available$/);
  if (available) return language === 'uk' ? `Доступно: ${available[1]} ${available[2]} Sparks` : `Доступно: ${available[1]} ${available[2]} Sparks`;
  const remaining = value.match(/^(\d+) remaining$/);
  if (remaining) return language === 'uk' ? `Залишилося: ${remaining[1]}` : `Осталось: ${remaining[1]}`;
  const genericAvailable = value.match(/^(\d+) available$/);
  if (genericAvailable) return language === 'uk' ? `Доступно: ${genericAvailable[1]}` : `Доступно: ${genericAvailable[1]}`;
  const nominationsAvailable = value.match(/^(\d+) nominations? available$/);
  if (nominationsAvailable) return language === 'uk' ? `Доступно номінацій: ${nominationsAvailable[1]}` : `Доступно номинаций: ${nominationsAvailable[1]}`;
  const allocation = value.match(/^(Q\d \d{4}) allocation$/);
  if (allocation) return language === 'uk' ? `Квота ${allocation[1]}` : `Квота ${allocation[1]}`;
  const activeCategories = value.match(/^(\d+) active categories$/);
  if (activeCategories) return language === 'uk' ? `${activeCategories[1]} активних категорій` : `${activeCategories[1]} активных категорий`;
  const categoryAllowance = value.match(/^(\d+) (Yellow|Blue) · one category per employee per quarter$/);
  if (categoryAllowance) return language === 'uk'
    ? `${categoryAllowance[1]} ${categoryAllowance[2]} · одна категорія на працівника за квартал`
    : `${categoryAllowance[1]} ${categoryAllowance[2]} · одна категория на сотрудника за квартал`;
  const needMore = value.match(/^You need (\d+) more (White|Yellow|Blue) Sparks for this conversion\.$/);
  if (needMore) return language === 'uk'
    ? `Для цієї конвертації потрібно ще ${needMore[1]} ${needMore[2]} Sparks.`
    : `Для этой конвертации нужно ещё ${needMore[1]} ${needMore[2]} Sparks.`;
  const awardedBy = value.match(/^Awarded by (.+)$/);
  if (awardedBy) return language === 'uk' ? `Нагородив: ${awardedBy[1]}` : `Наградил: ${awardedBy[1]}`;
  const seeMore = value.match(/^See more \((\d+)\)$/);
  if (seeMore) return language === 'uk' ? `Показати ще (${seeMore[1]})` : `Показать ещё (${seeMore[1]})`;
  const showMoreAchievements = value.match(/^Show more achievements \((\d+)\)$/);
  if (showMoreAchievements) return language === 'uk' ? `Показати більше досягнень (${showMoreAchievements[1]})` : `Показать больше достижений (${showMoreAchievements[1]})`;
  const gateUntil = value.match(/^Gate until (.+)$/);
  if (gateUntil) return language === 'uk' ? `Обмеження до ${gateUntil[1]}` : `Ограничение до ${gateUntil[1]}`;
  const monthlyAccounting = value.match(/^Monthly accounting · (.+)$/);
  if (monthlyAccounting) return language === 'uk' ? `Щомісячна бухгалтерія · ${monthlyAccounting[1]}` : `Ежемесячная бухгалтерия · ${monthlyAccounting[1]}`;
  const displayDate = value.match(/^(MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY) (\d{1,2}) (JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)$/i);
  if (displayDate) {
    const weekdays = language === 'uk'
      ? ['ПОНЕДІЛОК', 'ВІВТОРОК', 'СЕРЕДА', 'ЧЕТВЕР', 'П’ЯТНИЦЯ', 'СУБОТА', 'НЕДІЛЯ']
      : ['ПОНЕДЕЛЬНИК', 'ВТОРНИК', 'СРЕДА', 'ЧЕТВЕРГ', 'ПЯТНИЦА', 'СУББОТА', 'ВОСКРЕСЕНЬЕ'];
    const months = language === 'uk'
      ? ['СІЧНЯ', 'ЛЮТОГО', 'БЕРЕЗНЯ', 'КВІТНЯ', 'ТРАВНЯ', 'ЧЕРВНЯ', 'ЛИПНЯ', 'СЕРПНЯ', 'ВЕРЕСНЯ', 'ЖОВТНЯ', 'ЛИСТОПАДА', 'ГРУДНЯ']
      : ['ЯНВАРЯ', 'ФЕВРАЛЯ', 'МАРТА', 'АПРЕЛЯ', 'МАЯ', 'ИЮНЯ', 'ИЮЛЯ', 'АВГУСТА', 'СЕНТЯБРЯ', 'ОКТЯБРЯ', 'НОЯБРЯ', 'ДЕКАБРЯ'];
    const dayIndex = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'].indexOf(displayDate[1].toUpperCase());
    const monthIndex = ['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'].indexOf(displayDate[3].toUpperCase());
    return `${weekdays[dayIndex]} ${displayDate[2]} ${months[monthIndex]}`;
  }
  const shortDate = value.match(/^(\d{1,2}) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)(,? .*)?$/);
  if (shortDate) {
    const monthIndex = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].indexOf(shortDate[2]);
    const months = language === 'uk'
      ? ['січ.', 'лют.', 'бер.', 'квіт.', 'трав.', 'черв.', 'лип.', 'серп.', 'вер.', 'жовт.', 'лист.', 'груд.']
      : ['янв.', 'февр.', 'мар.', 'апр.', 'мая', 'июн.', 'июл.', 'авг.', 'сент.', 'окт.', 'нояб.', 'дек.'];
    return `${shortDate[1]} ${months[monthIndex]}${shortDate[3] ?? ''}`;
  }
  return value;
};

export function localizeContent(language: InterfaceLanguage, value: string) {
  if (language === 'en') return value;
  const trimmed = value.trim();
  if (!trimmed) return value;
  const translated = maps[language][trimmed] ?? dynamic(language, trimmed);
  if (translated === trimmed) return value;
  return value.replace(trimmed, translated);
}
