import type {
  ProductRarity,
  ShopCategoryFilter,
  ShopSort,
} from '@/models/shop';

export const SHOP_TEXT = {
  navigation: {
    shop: 'Reward Shop',
    inventory: 'My Purchases',
  },
  shop: {
    eyebrow: 'Rewards marketplace',
    title: 'Reward Shop',
    description: 'Spend your existing White, Yellow and Blue Sparks on abilities and exclusive rewards.',
    balanceLabel: 'Your spendable Sparks',
    balanceSource: 'Synced with My Sparks · Radiant remains permanent',
    retry: 'Try again',
    emptyTitle: 'No rewards match these filters',
    emptyDescription: 'Choose another category or sorting option to discover more rewards.',
    resetFilters: 'Show all items',
  },
  inventory: {
    eyebrow: 'Personal collection',
    title: 'My Purchases',
    description: 'Activate purchased rewards and keep track of their availability.',
    emptyTitle: 'Your inventory is empty',
    emptyDescription: 'Visit the shop and choose your first reward.',
    goToShop: 'Go to Reward Shop',
    historyTitle: 'Transaction History',
    historyDescription: 'Your purchase activity is recorded in one ledger.',
    unavailable: 'Your inventory is currently unavailable.',
    acquiredItems: 'Purchased items',
    activationInProgress: 'Activating…',
    statuses: {
      Owned: 'Ready to use',
      Active: 'Activated',
      Used: 'Used',
      Expired: 'Expired',
    },
  },
  purchase: {
    title: 'Confirm purchase',
    currentBalance: 'Current balance',
    afterPurchase: 'Balance after purchase',
    cancel: 'Cancel',
    confirm: 'Confirm purchase',
    processing: 'Purchasing…',
    successTitle: 'Purchase complete!',
    successDescription: 'The reward is now available in your inventory.',
    openInventory: 'Open inventory',
    continueShopping: 'Continue shopping',
    insufficientTitle: 'Not enough Sparks',
    insufficientDescription: (missing: number, sparkType: string) =>
      `You need ${missing.toLocaleString('en-US')} more ${sparkType} ${missing === 1 ? 'Spark' : 'Sparks'}. Earn or convert Sparks to complete this purchase.`,
    earnSparks: 'Go to My Sparks',
    serverCheck: 'The latest Spark price and your available balance are checked before charging.',
    atomicOperation: 'The Spark debit and purchase record are completed as one protected operation.',
    balance: 'Balance',
    missing: 'Missing',
    close: 'Close',
    newBalance: 'New balance',
  },
  actions: {
    buy: 'Buy',
    insufficient: 'Not enough Sparks',
    purchased: 'Already purchased',
    use: 'Use',
    activate: 'Activate',
    activated: 'Activated',
    soldOut: 'Sold out',
    soon: 'Coming soon',
    processing: 'Processing…',
  },
  labels: {
    price: 'Price',
    category: 'Category',
    rarity: 'Rarity',
    duration: 'Duration',
    purchasedAt: 'Purchased',
    expiresAt: 'Available until',
    transactionId: 'Transaction ID',
    new: 'New',
    hit: 'Popular',
    limited: 'Limited',
  },
  status: {
    loading: 'Loading rewards…',
    activationSuccess: 'Item activated.',
    identityRequired: 'Your signed-in C-Job account could not be verified. Sign in again to continue.',
    balanceUnavailable: 'Balance unavailable',
    balanceLoading: 'Loading your Spark balances',
    loadingCatalog: 'Loading catalog',
    loadingProducts: 'Loading Reward Shop items…',
  },
  product: {
    remaining: (stock: number) => `${stock} remaining`,
    balanceCoverage: (percentage: number) => `Your balance covers ${percentage} percent of the item price`,
    imageAlt: (name: string) => `${name} reward artwork`,
  },
  aria: {
    filters: 'Catalog filters',
    categories: 'Reward categories',
    sort: 'Sort rewards',
    catalog: 'Reward catalog',
    productAction: (action: string, name: string, price: string) => `${action}: ${name}, ${price}`,
  },
  history: {
    eyebrow: 'Reward Shop activity',
    title: 'Transaction History',
    immutable: 'Transactions cannot be edited or deleted.',
    empty: 'There are no transactions yet.',
    completed: 'Completed',
    purchase: 'Purchase',
    credit: 'Credit',
    manualCredit: 'Manual credit',
    manualDebit: 'Manual debit',
  },
  errors: {
    genericOperation: 'The shop operation could not be completed.',
    loadShop: 'The Reward Shop could not be loaded.',
    purchaseInProgress: 'A purchase is already being processed.',
    finishPurchase: 'The purchase could not be completed.',
    activateItem: 'The item could not be activated.',
    loadAdmin: 'Shop management could not be loaded.',
    saveProduct: 'The item could not be saved.',
    uploadImage: 'The image could not be uploaded.',
    adjustBalance: 'The balance could not be adjusted.',
  },
  admin: {
    catalogEyebrow: 'Catalog management',
    catalogTitle: 'Shop items',
    catalogDescription: 'Price, rarity, stock and availability are checked by the server for every purchase.',
    addProduct: 'Add item',
    unlimited: 'unlimited',
    units: 'units',
    active: 'Active',
    disabled: 'Disabled',
    edit: 'Edit',
    balanceEyebrow: 'Controlled adjustment',
    balanceTitle: 'Adjust Spark balance',
    user: 'User',
    userAria: 'User whose balance will be adjusted',
    sparkType: 'Spark type',
    sparkTypeAria: 'Spark type to adjust',
    signedAmount: 'Signed Spark amount',
    amountPlaceholder: 'For example, 2 or -1',
    reason: 'Required reason',
    reasonPlaceholder: 'Explain why this balance must change',
    confirmAdjustment: 'Confirm adjustment',
    noUsers: 'Users will appear after they open the Reward Shop for the first time.',
    purchasesEyebrow: 'Purchase overview',
    purchasesTitle: 'Recent purchases',
    noPurchases: 'No purchases yet.',
    legacyPurchase: 'Legacy purchase',
    editProduct: 'Edit item',
    newProduct: 'New item',
    editorDescription: 'Catalog fields are stored in the server database.',
    uploading: 'Uploading…',
    uploadImage: 'Upload image',
    name: 'Name',
    description: 'Description',
    price: 'Spark price',
    priceSparkType: 'Price Spark type',
    priceSparkTypeAria: 'Spark type used to buy this item',
    stock: 'Stock',
    stockPlaceholder: 'Unlimited',
    category: 'Category',
    categoryAria: 'Item category',
    rarity: 'Rarity',
    rarityAria: 'Item rarity',
    productType: 'Item type',
    productTypeAria: 'Item type',
    icon: 'Icon',
    iconAria: 'Item icon',
    duration: 'Duration in hours',
    durationPlaceholder: 'No time limit',
    availableFrom: 'Offer starts',
    availableUntil: 'Offer ends',
    state: 'Item state',
    featured: 'Featured',
    limited: 'Limited',
    cancel: 'Cancel',
    save: 'Save item',
    productSaved: 'The item was saved and the catalog was refreshed.',
    balanceSaved: 'The Spark balance was updated and the transaction was added to the ledger.',
  },
} as const;

export const PRODUCT_TYPE_OPTIONS = [
  { value: 'Consumable', label: 'Consumable' },
  { value: 'Activatable', label: 'Activatable' },
  { value: 'Permanent', label: 'Permanent' },
] as const;

export const PRODUCT_ICON_OPTIONS = [
  { value: 'gift', label: 'Gift' },
  { value: 'zap', label: 'Boost' },
  { value: 'shield', label: 'Protection' },
  { value: 'palette', label: 'Theme' },
  { value: 'crown', label: 'Crown' },
  { value: 'badge', label: 'Badge' },
  { value: 'rotate', label: 'Reroll' },
  { value: 'package', label: 'Bundle' },
  { value: 'gem', label: 'Gem' },
] as const;

export const SHOP_CATEGORIES: Array<{ value: ShopCategoryFilter; label: string }> = [
  { value: 'All', label: 'All items' },
  { value: 'Popular', label: 'Popular' },
  { value: 'Boosters', label: 'Boosters' },
  { value: 'Customization', label: 'Customization' },
  { value: 'Features', label: 'Abilities' },
  { value: 'Exclusive', label: 'Exclusive' },
];

export const SHOP_SORTS: Array<{ value: ShopSort; label: string }> = [
  { value: 'popular', label: 'Most popular' },
  { value: 'price-asc', label: 'Price: low to high' },
  { value: 'price-desc', label: 'Price: high to low' },
  { value: 'newest', label: 'Newest' },
];

export const RARITY_LABELS: Record<ProductRarity, string> = {
  Common: 'Common',
  Rare: 'Rare',
  Epic: 'Epic',
  Legendary: 'Legendary',
};
